export const coinList = [
  { currency: 'BTC', country: 'Bitcoin' },
  { currency: 'ETH', country: 'Ethereum' },
  { currency: 'XRP', country: 'Ripple' },
  { currency: 'LTC', country: 'Litecoin' },
  { currency: 'DASH', country: 'Dash' },
  { currency: 'BCH', country: 'Bitcoin cash' },
  { currency: 'ZEC', country: 'Zcash' },
  { currency: 'XMR', country: 'Monero' },
  { currency: 'XLM', country: 'Stellar' },
  { currency: 'VTC', country: 'Vertcoin' },
  { currency: 'WAVES', country: 'Waves' },
  { currency: 'START', country: 'Stratis' },
  { currency: 'DCR', country: 'Decred' },
  { currency: 'XEM', country: 'NEM' },
  { currency: 'ETC', country: 'Ethereum Classic' },
  { currency: 'BCN', country: 'Bytecoin' },
  { currency: 'DGB', country: 'Digibyte' },
  { currency: 'DOGE', country: 'Dogecoin' },
  { currency: 'BTS', country: 'Bitshares' },
  { currency: 'NXT', country: 'Nxt' },
  { currency: 'SC', country: 'Siacoin' },
]
